### ISSUE TITLE
upload docs to rtfd etc

### ISSUE THREAD

**Issue by graingert** [jreese/fissix#23] opened 2020-09-03 09:37 UTC
### Description
I'd like to link from https://modernize.readthedocs.io/en/latest/fixers.html#to3-fixers to fissix but there's no docs page on https://fissix.readthedocs.io/

**Comment by jreese** [comment] 2020-09-03 16:26
What documentation are you wanting/expecting to see? Just generated autodocs, or are you looking for a duplicate of the cpython docs you already link to?

**Comment by graingert** [comment] 2020-09-03 16:41
@jreese mostly a duplicate, but with lib2to3 swapped out for fissix, etc.

**Comment by graingert** [comment] 2020-09-03 16:41
and if fixes start getting added here, the docs would need to be updated here too

**Closed** 2020-09-03 17:33 UTC

**Comment by jreese** [comment] 2020-09-03 17:46
https://fissix.readthedocs.io/en/latest/
